name: Bug
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: has-searched-issues
    attributes:
      label: Is there an existing issue for this?
      description: Have you searched the existing issues for this feature request?
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What went wrong?
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Describe the actions that led up to the bug
      placeholder: Steps to reproduce the behavior
      value: |
        1. Go to ...
        2. Click on ...
        3. See the error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here
    validations:
      required: false
  - type: textarea
    id: device-info
    attributes:
      label: Device Info
      description: |
        **Please complete the following information**
        - Discord Music Presence version: [e.g. 2.0.0]
        - Operating system: [e.g. Windows]
        - The media player you used (if applicable): [e.g. Spotify]
      value: |
        - Discord Music Presence version: [e.g. 2.0.0]
        - Operating system: [e.g. Windows]
        - The media player you used (if applicable): [e.g. Spotify]
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Anything else we should know?
    validations:
      required: false
